/*
   Copyright (C) 2021 Xcalibyte (Shenzhen) Limited.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

//
// ====================================================================
// AUTOSAR_enum.inc
// ====================================================================
//
// the defines of about the AUTOSAR rules
//

#define AUTOSAR   "AUTOSAR"
#define A5_0_3    "A5_0_3"
#define A5_1_1    "A5_1_1"
#define A5_1_2    "A5_1_2"
#define A5_1_3    "A5_1_3"
#define A5_1_6    "A5_1_6"
#define A5_1_7    "A5_1_7"
#define A5_1_8    "A5_1_8"
#define A5_16_1   "A5_16_1"
#define A7_1_6    "A7_1_6"
#define A7_1_7    "A7_1_7"
#define A7_2_2    "A7_2_2"
#define A7_2_3    "A7_2_3"
#define A7_2_4    "A7_2_4"
#define A7_3_3    "A7_3_3"
#define A7_3_4    "A7_3_4"
#define A7_3_6    "A7_3_6"
#define A7_5_2    "A7_5_2"
#define A8_2_1    "A8_2_1"
#define A9_3_1    "A9_3_1"
#define A10_1_1   "A10_1_1"
#define A10_3_1   "A10_3_1"
#define A10_3_2   "A10_3_2"
#define A10_3_3   "A10_3_3"
#define A10_3_5   "A10_3_5"
#define A11_0_1   "A11_0_1"
#define A11_0_2   "A11_0_2"
#define A11_3_1   "A11_3_1"
#define A12_1_6   "A12_1_6"
#define A12_4_1   "A12_4_1"
#define A12_4_2   "A12_4_2"
#define A12_8_7   "A12_8_7"
#define A13_1_2   "A13_1_2"
#define A13_2_1   "A13_2_1"
#define A13_2_2   "A13_2_2"
#define A13_2_3   "A13_2_3"
#define A13_5_1   "A13_5_1"
#define A13_5_2   "A13_5_2"
#define A13_5_3   "A13_5_3"
#define A13_5_5   "A13_5_5"
