/*
   Copyright (C) 2021 Xcalibyte (Shenzhen) Limited.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

//
// ====================================================================
// AUTOSAR_enum.inc
// ====================================================================
//
// the defines of about the AUTOSAR rules
//

#define AUTOSAR   "autosar"
#define A5_1_1    "A5_1_1"
#define A5_1_2    "A5_1_2"
#define A5_1_3    "A5_1_3"
#define A5_1_6    "A5_1_6"
#define A7_2_2    "A7_2_2"
#define A7_2_3    "A7_2_3"
#define A7_3_3    "A7_3_3"
#define A7_3_4    "A7_3_4"
#define A7_3_6    "A7_3_6"
