/*
 * Copyright (C) 2020-2021 Xcalibyte Limited, Inc.  All Rights Reserved.
 */

//
// ====================================================================
// cert_enum.inc
// ====================================================================
//
// the defines of about the CERT rules
//

#define CERT        "CERT"
#define DCL_30_C    "DCL_30_C"
#define DCL_31_C    "DCL_31_C"
#define DCL_37_C    "DCL_37_C"
#define DCL_38_C    "DCL_38_C"
