/*
   Copyright (C) 2021 Xcalibyte (Shenzhen) Limited.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

//
// ====================================================================
// MISRA_enum.inc
// ====================================================================
//
// the defines of about the MISRA rules
//

#define MISRA       "MISRA"
#define M_R_2_3     "MSR_2_3"
#define M_R_2_4     "MSR_2_4"
#define M_R_2_5     "MSR_2_5"
#define M_R_2_6     "MSR_2_6"
#define M_R_2_7     "MSR_2_7"
#define M_R_4_2     "M_R_4_2"

#define M_R_5_1     "MSR_5_1"
#define M_R_5_2     "MSR_5_2"
#define M_R_5_3     "MSR_5_3"
#define M_R_5_4     "MSR_5_4"
#define M_R_5_5     "MSR_5_5"Ï
#define M_R_5_6     "MSR_5_6"
#define M_R_5_7     "MSR_5_7"


#define M_R_6_1     "MSR_6_1"
#define M_R_7_4     "MSR_7_4"
#define M_R_8_4     "MSR_8_4"
#define M_R_8_8     "MSR_8_8"
#define M_R_8_10    "MSR_8_10"
#define M_R_8_11    "MSR_8_11"
#define M_R_8_12    "MSR_8_12"
#define M_R_8_13    "MSR_8_13"
#define M_R_8_14    "MSR_8_14"

#define M_R_9_3     "MSR_9_3"
#define M_R_9_4     "MSR_9_4"

#define M_R_10_2    "MSR_10_2"
#define M_R_10_3    "MSR_10_3"
#define M_R_10_4    "MSR_10_4"
#define M_R_10_6    "MSR_10_6"
#define M_R_10_7    "MSR_10_7"
#define M_R_10_8    "MSR_10_8"

#define M_R_11_4    "MSR_11_4"
#define M_R_11_5    "MSR_11_5"
#define M_R_11_6    "MSR_11_6"
#define M_R_11_7    "MSR_11_7"
#define M_R_11_8    "MSR_11_8"
#define M_R_11_9    "MSR_11_9"
#define M_R_11_10   "MSR_11_10"
#define M_R_12_1    "MSR_12_1"
#define M_R_12_2    "MSR_12_2"
#define M_R_12_3    "MSR_12_3"
#define M_R_12_4    "MSR_12_4"

#define M_R_13_1    "MSR_13_1"
#define M_R_13_2    "MSR_13_2"
#define M_R_13_4    "MSR_13_4"
#define M_R_13_5    "MSR_13_5"
#define M_R_13_6    "MSR_13_6"
#define M_R_13_7    "MSR_13_7"
#define M_R_14_1    "MSR_14_1"
#define M_R_14_4    "MSR_14_4"
#define M_R_15_2    "MSR_15_2"
#define M_R_15_3    "MSR_15_3"
#define M_R_15_4    "MSR_15_4"

#define M_R_16_4    "MSR_16_4"
#define M_R_16_5    "MSR_16_5"
#define M_R_16_6    "MSR_16_6"
#define M_R_16_7    "MSR_16_7"
#define M_R_16_8    "MSR_16_8"
#define M_R_17_1    "MSR_17_1"
#define M_R_17_5    "MSR_17_5"
#define M_R_17_6    "MSR_17_6"
#define M_R_17_7    "MSR_17_7"
#define M_R_17_8    "MSR_17_8"

#define M_R_18_4    "MSR_18_4"
#define M_R_18_7    "MSR_18_7"
#define M_R_18_8    "MSR_18_8"
#define M_R_19_2    "MSR_19_2"
#define M_R_21_3    "MSR_21_3"
#define M_R_21_4    "MSR_21_4"
#define M_R_21_5    "MSR_21_5"
#define M_R_21_6    "MSR_21_6"
#define M_R_21_7    "MSR_21_7"
#define M_R_21_8    "MSR_21_8"
#define M_R_21_9    "MSR_21_9"
#define M_R_21_10   "MSR_21_10"
#define M_R_21_11   "MSR_21_11"
#define M_R_21_12   "MSR_21_12"

// misra cpp
#define M_R_5_0_19   "MSR_5_0_19"
#define M_R_5_2_2    "MSR_5_2_2"
#define M_R_5_2_3    "MSR_5_2_3"

#define M_R_8_3_1    "MSR_8_3_1"
#define M_R_8_5_3    "MSR_8_5_3"
#define M_R_10_1_3   "MSR_10_1_3"
#define M_R_10_2_1   "MSR_10_2_1"
#define M_R_10_3_2   "MSR_10_3_2"
#define M_R_11_0_1   "MSR_11_0_1"
#define M_R_12_1_1   "MSR_12_1_1"
#define M_R_12_1_2   "MSR_12_1_2"
#define M_R_12_1_3   "MSR_12_1_3"
#define M_R_12_8_1   "MSR_12_8_1"
#define M_R_12_8_2   "MSR_12_8_2"
#define M_R_14_5_2   "MSR_14_5_2"
#define M_R_14_5_3   "MSR_14_5_3"
#define M_R_15_0_2   "MSR_15_0_2"
#define M_R_15_1_1   "MSR_15_1_1"
#define M_R_15_1_2   "MSR_15_1_2"
#define M_R_15_1_3   "MSR_15_1_3"
#define M_R_15_3_2   "MSR_15_3_2"
#define M_R_15_3_4   "MSR_15_3_4"
#define M_R_15_3_5   "MSR_15_3_5"
#define M_R_15_3_7   "MSR_15_3_7"
#define M_R_15_4_1   "MSR_15_4_1"
#define M_R_15_5_1   "MSR_15_5_1"
#define M_R_15_5_2   "MSR_15_5_2"


#define M_R_99_99_99   "MSR_99_99_99"
