/*
 * Copyright (C) 2020-2021 Xcalibyte Limited, Inc.  All Rights Reserved.
 */

//
// ====================================================================
// MISRA_enum.inc
// ====================================================================
//
// the defines of about the MISRA rules
//

#define MISRA       "MISRA"
#define M_R_2_3     "M_R_2_3"
#define M_R_2_4     "M_R_2_4"
#define M_R_2_5     "M_R_2_5"
#define M_R_2_6     "M_R_2_6"
#define M_R_2_7     "M_R_2_7"

#define M_R_5_1     "M_R_5_1"
#define M_R_5_2     "M_R_5_2"
#define M_R_5_3     "M_R_5_3"
#define M_R_5_4     "M_R_5_4"
#define M_R_5_5     "M_R_5_5"
#define M_R_5_6     "M_R_5_6"
#define M_R_5_7     "M_R_5_7"


#define M_R_6_1     "M_R_6_1"
#define M_R_7_4     "M_R_7_4"
#define M_R_8_4     "M_R_8_4"
#define M_R_8_10    "M_R_8_10"
#define M_R_8_11    "M_R_8_11"
#define M_R_8_12    "M_R_8_12"
#define M_R_8_13    "M_R_8_13"
#define M_R_8_14    "M_R_8_14"

#define M_R_9_3     "M_R_9_3"
#define M_R_9_4     "M_R_9_4"

#define M_R_10_2    "M_R_10_2"
#define M_R_10_3    "M_R_10_3"
#define M_R_10_4    "M_R_10_4"
#define M_R_10_5    "M_R_10_5"
#define M_R_10_6    "M_R_10_6"
#define M_R_10_7    "M_R_10_7"
#define M_R_10_8    "M_R_10_8"

#define M_R_11_4    "M_R_11_4"
#define M_R_11_5    "M_R_11_5"
#define M_R_11_6    "M_R_11_6"
#define M_R_11_7    "M_R_11_7"
#define M_R_11_8    "M_R_11_8"
#define M_R_11_9    "M_R_11_9"
#define M_R_11_10   "M_R_11_10"
#define M_R_12_1    "M_R_12_1"
#define M_R_12_2    "M_R_12_2"
#define M_R_12_3    "M_R_12_3"

#define M_R_13_4    "M_R_13_4"
#define M_R_13_5    "M_R_13_5"
#define M_R_13_6    "M_R_13_6"
#define M_R_13_7    "M_R_13_7"
#define M_R_14_4    "M_R_14_4"
#define M_R_15_2    "M_R_15_2"
#define M_R_15_3    "M_R_15_3"
#define M_R_15_4    "M_R_15_4"

#define M_R_16_5    "M_R_16_5"
#define M_R_16_6    "M_R_16_6"
#define M_R_16_7    "M_R_16_7"
#define M_R_16_8    "M_R_16_8"
#define M_R_17_1    "M_R_17_1"
#define M_R_17_5    "M_R_17_5"
#define M_R_17_6    "M_R_17_6"
#define M_R_17_7    "M_R_17_7"
#define M_R_17_8    "M_R_17_8"

#define M_R_18_4    "M_R_18_4"
#define M_R_18_7    "M_R_18_7"
#define M_R_18_8    "M_R_18_8"
#define M_R_19_2    "M_R_19_2"
#define M_R_21_3    "M_R_21_3"
#define M_R_21_5    "M_R_21_5"
#define M_R_21_7    "M_R_21_7"
